export const categoriesOutcome = [
    {
        key: "rent",
        name: "Aluguel",
        icon: "home-outline",
        color: "#1C3EBD",
    },
    {
        key: "condominium",
        name: "Condomínio",
        icon: "file-document-outline",
        color: "#552998",
    },
    {
        key: "purchases",
        name: "Compras",
        icon: "shopping-outline",
        color: "#077A9B",
    },
    {
        key: "food",
        name: "Alimentação",
        icon: "food-outline",
        color: "#FF872C",
    },
    {
        key: "supermarket",
        name: "Supermercado",
        icon: "cart-variant",
        color: "#0A6407",
    },
    { key: "water", name: "Água", icon: "water-outline", color: "#1F86DE" },
    { key: "light", name: "Luz", icon: "lightbulb-outline", color: "#F0980C" },
    { key: "net", name: "Internet", icon: "wifi", color: "#0CF07C" },
    { key: "gas", name: "Gás", icon: "propane-tank-outline", color: "#56665E" },
    { key: "bank", name: "Bancos", icon: "bank-outline", color: "#982EC9" },
    { key: "car", name: "Carro", icon: "car-outline", color: "#C96A2E" },
    { key: "fuel", name: "Combustível", icon: "fuel", color: "#EC3434" },
    {
        key: "card",
        name: "Cartão de crédito",
        icon: "card-bulleted-outline",
        color: "#281D73",
    },
    {
        key: "pet",
        name: "Veterinário/Pet",
        icon: "cat",
        color: "#0006FF",
    },
    {
        key: "tool",
        name: "Consertos",
        icon: "tools",
        color: "#AF871A",
    },
    {
        key: "tol",
        name: "Taxas/impostos",
        icon: "hand-coin-outline",
        color: "#AF3155",
    },
    {
        key: "phone",
        name: "Telefone/celular",
        icon: "phone-outline",
        color: "#0D856E",
    },
    {
        key: "dentist",
        name: "Dentista",
        icon: "tooth-outline",
        color: "#9900E6",
    },
    {
        key: "doctor",
        name: "Consultas médicas",
        icon: "doctor",
        color: "#003E97",
    },
    {
        key: "spa",
        name: "Cuidados pessoais",
        icon: "spa-outline",
        color: "#229729",
    },
    {
        key: "health",
        name: "Saúde",
        icon: "heart-outline",
        color: "#F90000",
    },
    {
        key: "pharmacy",
        name: "Farmácia",
        icon: "medical-bag",
        color: "#BF0000",
    },
    {
        key: "monitor",
        name: "Monitoramento",
        icon: "eye-outline",
        color: "#88BF69",
    },
    {
        key: "ensurance",
        name: "Seguros",
        icon: "shield-key-outline",
        color: "#7B1007",
    },
    {
        key: "saving",
        name: "Aplicações",
        icon: "bank-outline",
        color: "#005D95",
    },
    {
        key: "tv",
        name: "Televisão/streaming",
        icon: "television-classic",
        color: "#00A7E6",
    },
    { key: "leisure", name: "Lazer", icon: "palm-tree", color: "#84CB1D" },
    {
        key: "studies",
        name: "Estudos",
        icon: "book-open-outline",
        color: "#0B507C",
    },
    { key: "gim", name: "Academia", icon: "weight-lifter", color: "#7CA2BE" },
    {
        key: "debt",
        name: "Dívidas/boletos",
        icon: "credit-card-clock-outline",
        color: "#D65D5D",
    },
    {
        key: "outothers",
        name: "Outros",
        icon: "basket-outline",
        color: "#333434",
    },
];

export const categoriesIncome = [
    {
        key: "salary",
        name: "Salário",
        icon: "account-cash-outline",
        color: "#147819",
    },
    {
        key: "voucher",
        name: "Vale alimentação",
        icon: "food-apple-outline",
        color: "#F18C2D",
    },
    {
        key: "vacation",
        name: "Férias",
        icon: "beach",
        color: "#144178",
    },
    {
        key: "13",
        name: "13° salário",
        icon: "calendar-outline",
        color: "#781473",
    },
    {
        key: "sales",
        name: "Vendas",
        icon: "hand-extended-outline",
        color: "#784B14",
    },
    {
        key: "exit",
        name: "Rescisão",
        icon: "exit-run",
        color: "#088EA9",
    },
    {
        key: "inothers",
        name: "Outras entradas",
        icon: "archive-arrow-down-outline",
        color: "#461BBA",
    },
];

export const commonCategories = [
    {
        key: "salary",
        name: "Salário",
        icon: "account-cash-outline",
        color: "#147819",
    },
    {
        key: "voucher",
        name: "Vale alimentação",
        icon: "food-apple-outline",
        color: "#F18C2D",
    },
    {
        key: "vacation",
        name: "Férias",
        icon: "beach",
        color: "#144178",
    },
    {
        key: "13",
        name: "13° salário",
        icon: "calendar-outline",
        color: "#781473",
    },
    {
        key: "sales",
        name: "Vendas",
        icon: "hand-extended-outline",
        color: "#784B14",
    },
    {
        key: "exit",
        name: "Rescisão",
        icon: "exit-run",
        color: "#088EA9",
    },
    {
        key: "inothers",
        name: "Outras entradas",
        icon: "archive-arrow-down-outline",
        color: "#461BBA",
    },
    {
        key: "rent",
        name: "Aluguel",
        icon: "home-outline",
        color: "#1C3EBD",
    },
    {
        key: "condominium",
        name: "Condomínio",
        icon: "file-document-outline",
        color: "#552998",
    },
    {
        key: "purchases",
        name: "Compras",
        icon: "shopping-outline",
        color: "#077A9B",
    },
    {
        key: "food",
        name: "Alimentação",
        icon: "food-outline",
        color: "#FF872C",
    },
    {
        key: "supermarket",
        name: "Supermercado",
        icon: "cart-variant",
        color: "#0A6407",
    },
    {
        key: "pharmacy",
        name: "Farmácia",
        icon: "medical-bag",
        color: "#BF0000",
    },
    { key: "water", name: "Água", icon: "water-outline", color: "#1F86DE" },
    { key: "light", name: "Luz", icon: "lightbulb-outline", color: "#F0980C" },
    { key: "net", name: "Internet", icon: "wifi", color: "#0CF07C" },
    { key: "gas", name: "Gás", icon: "propane-tank-outline", color: "#56665E" },
    { key: "bank", name: "Bancos", icon: "bank-outline", color: "#982EC9" },
    { key: "car", name: "Carro", icon: "car-outline", color: "#C96A2E" },
    { key: "fuel", name: "Combustível", icon: "fuel", color: "#EC3434" },
    {
        key: "card",
        name: "Cartão de crédito",
        icon: "card-bulleted-outline",
        color: "#281D73",
    },
    {
        key: "pet",
        name: "Veterinário/Pet",
        icon: "cat",
        color: "#0006FF",
    },
    {
        key: "tool",
        name: "Consertos",
        icon: "tools",
        color: "#AF871A",
    },
    {
        key: "health",
        name: "Saúde",
        icon: "heart-outline",
        color: "#F90000",
    },
    {
        key: "spa",
        name: "Cuidados pessoais",
        icon: "spa-outline",
        color: "#229729",
    },
    {
        key: "tol",
        name: "Taxas/impostos",
        icon: "hand-coin-outline",
        color: "#AF3155",
    },
    {
        key: "phone",
        name: "Telefone/celular",
        icon: "phone-outline",
        color: "#0D856E",
    },
    {
        key: "dentist",
        name: "Dentista",
        icon: "tooth-outline",
        color: "#9900E6",
    },
    {
        key: "doctor",
        name: "Consultas médicas",
        icon: "doctor",
        color: "#003E97",
    },
    {
        key: "monitor",
        name: "Monitoramento",
        icon: "eye-outline",
        color: "#88BF69",
    },
    {
        key: "ensurance",
        name: "Seguros",
        icon: "shield-key-outline",
        color: "#7B1007",
    },
    {
        key: "saving",
        name: "Aplicações",
        icon: "bank-outline",
        color: "#005D95",
    },
    {
        key: "tv",
        name: "Televisão/streaming",
        icon: "television-classic",
        color: "#00A7E6",
    },
    { key: "leisure", name: "Lazer", icon: "palm-tree", color: "#84CB1D" },
    {
        key: "studies",
        name: "Estudos",
        icon: "book-open-outline",
        color: "#0B507C",
    },
    { key: "gim", name: "Academia", icon: "weight-lifter", color: "#7CA2BE" },
    {
        key: "debt",
        name: "Dívidas/boletos",
        icon: "credit-card-clock-outline",
        color: "#D65D5D",
    },
    {
        key: "outothers",
        name: "Outros",
        icon: "basket-outline",
        color: "#333434",
    },
];
